CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Have you heard about BILL?\p"
    .string "Everyone calls him a POKéMANIAC!\p"
    .string "I think people are just jealous of\n"
    .string "BILL, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their POKéMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "i got a bulbasaur in this cage here$"
